[package]
name = "henad-compute"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
henad-core = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
flume = { workspace = true }
log = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
pollster = { workspace = true }

[[bench]]
name = "scatter"
harness = false

[lints]
workspace = true
