//! Model metadata derived from given information.

use crate::authoring::model::gpu_agent_model::{BufferSpec, PassSpec};
use crate::topology::NeighborhoodKind;

/// Model backend.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Backend {
    Cpu,
    Gpu,
}

impl Backend {
    pub fn label(self) -> &'static str {
        match self {
            Self::Cpu => "CPU",
            Self::Gpu => "GPU",
        }
    }
}

/// One lane of a CPU agent model's struct-of-arrays storage.
///
/// Generated by `agent_lanes!`.
#[derive(Debug, Clone, Copy)]
pub struct LaneSpec {
    pub name: &'static str,
    /// Element type as written in the declaration.
    pub ty: &'static str,
    pub double_buffered: bool,
}

/// Model's data structure.
pub enum Structure {
    Grid {
        neighborhood: NeighborhoodKind,
    },
    Agents {
        /// Agents per chunk in a step pass.
        chunk: usize,
        lanes: &'static [LaneSpec],
        /// [`crate::authoring::model::agent_model::NeighborIndex::KIND`].
        index: &'static str,
        /// [`crate::authoring::model::field::FieldLayer::KIND`].
        field: &'static str,
    },
    GpuGrid {
        /// Ping-ponged buffer labels.
        buffers: &'static [&'static str],
        workgroup: u32,
    },
    GpuAgents {
        buffers: &'static [BufferSpec],
        passes: &'static [PassSpec],
        index: bool,
        display: bool,
        counters: usize,
    },
}

/// Model metadata to be displayed in the UI,
pub struct ModelMetadata {
    pub backend: Backend,
    /// Colours the display layer or the agent population draws from. `None` for a GPU agent
    /// model, whose shaders write RGBA directly and declare no palette.
    pub palette: Option<&'static [[u8; 4]]>,
    pub structure: Structure,
}
